version: '3'

services:
  lb:
    image: haproxy
    ports:
      - "8080:8080"
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.18.0.2 # Assign a static IP address to the lb service
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  userservice1:
    image: userservice
    environment:
      - APPID=1111
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.18.0.3 # Assign a static IP address to userservice1

  userservice2:
    image: userservice
    environment:
      - APPID=2222
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.18.0.4 # Assign a static IP address to userservice2

  userservice3:
    image: userservice
    environment:
      - APPID=3333
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.18.0.5 # Assign a static IP address to userservice3

  userservice4:
    image: userservice
    environment:
      - APPID=4444
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.18.0.6 # Assign a static IP address to userservice4

networks:
  marketplace:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16 # Define a subnet for your custom network
